{
 "title": "grafana",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GetMPMetricsTotalCount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_getMPMetricsInfo_total"
    }
   ]
  },
  {
   "title": "GetMPMetricsInfoTimed_mean_seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_getMPMetricsInfoTimed_mean_seconds"
    }
   ]
  },
  {
   "title": "GetMPMetricsInfo_Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_getMPMetricsInfo_total"
    }
   ]
  },
  {
   "title": "CPU_Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_cpu_processCpuLoad" }
   ]
  },
  {
   "title": "Mem_maxHeap_Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_memory_maxHeap_bytes" }
   ]
  }
 ]
}